name = "StructuralLegendre"
version = "0.1.0"
defaultTargets = ["StructuralLegendre"]

[[lean_lib]]
name = "StructuralLegendre"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"
