import bisect
import ctypes
import ctypes.util
import datetime
import os
import sys
import time

VERSION = "v1.0"

# ==========================================================================================
# prime_sieve_primesieve.py -- "primesieve mode"
#
# Every OTHER engine in this folder (prime_sieve_v1.py .. v4.py) links a small CUSTOM .c
# wrapper (prime_sieve_engine_v*.c) that calls into libprimesieve's INTERNAL segment-sieving
# functions, wrapped in this project's own parallel batching/orchestration machinery
# (orchestrator_v3.py, orchestrator_loop_v2.py -- workers, batches, a shared mmap buffer).
#
# THIS file is different on purpose: it calls libprimesieve's own PUBLIC, top-level C API
# function -- primesieve_generate_primes() -- DIRECTLY, with no custom engine, no batching,
# no orchestrator in between. primesieve's own segmented-sieve-of-Eratosthenes-plus-wheel-
# factorization implementation is, on its own declared domain (the uint64_t range), about as
# fast as this kind of thing gets -- faster than what this project's own batched engines
# achieve at the same depth, since those pay real overhead (per-batch jump_to() bootstrap
# calls, Python-side ProcessPoolExecutor coordination) that primesieve's own internal
# multi-threading avoids entirely by never leaving C in the first place. The trade a person
# makes by choosing THIS mode over Floor/Range/Exploration is exactly that domain limit: once
# a request would need to go past primesieve_get_max_stop() (2**64 - 1), this mode simply
# cannot follow it there (see generate_floor_windows()'s ceiling-clamp/WARNING) -- the other
# three modes have no such ceiling, at the cost of being slower.
#
# The ONLY thing this file adds beyond calling straight into libprimesieve is mapping its
# result onto this project's own on-disk format and folder layout -- write_prime_window()
# (PGS2), the PRIME_WINDOW_10p{N}_off_{offset}.bin filename convention, and the low-floor
# (0-6) splitting behaviour -- all three duplicated verbatim from prime_sieve_v3.py, so a
# floor generated through this mode is byte-for-byte indistinguishable, from every OTHER
# part of this application's point of view, from one generated by any other engine.
#
# ATTRIBUTION: this file calls into libprimesieve, an independent, third-party, open-source
# project by Kim Walisch -- NOT authored by, or part of, this project.
#   Source:  https://github.com/kimwalisch/primesieve
#   License: BSD (see that repository's own LICENSE file for the exact text)
#   This file only binds (via ctypes) to the SYSTEM-installed libprimesieve shared library
#   and calls its public C API (primesieve.h / doc/C_API.md in that repository) -- no
#   primesieve source code is copied into this file or this project.
# ==========================================================================================


# ------------------------------------------------------------------------------------------
# PGS2 output format + low-floor splitting -- duplicated verbatim from prime_sieve_v3.py.
# Every scanner file in this folder is kept independently runnable (no cross-imports between
# prime_sieve_v1/v2/v3/v4.py) -- this file follows that same established convention rather
# than importing from prime_sieve_v3.py, so it has no dependency on any OTHER engine's
# presence or correctness.
# ------------------------------------------------------------------------------------------

PGS_MAGIC = b"PGS2"


def encode_varint(value):
    """LEB128 unsigned varint: 7 data bits per byte, MSB = continuation flag. Duplicated
    verbatim from prime_sieve_v3.py."""
    if value < 0:
        raise ValueError("encode_varint requires a non-negative value")
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return bytes(out)


def write_prime_window(path, primes, generated_at=None):
    """Writes a sorted list of primes (ints, ascending) to `path` in PGS2 format.
    Duplicated verbatim from prime_sieve_v3.py -- see that file for the full format
    writeup."""
    if generated_at is None:
        generated_at = int(time.time())
    count = len(primes)
    with open(path, "wb") as f:
        f.write(PGS_MAGIC)
        if count == 0:
            f.write(bytes([0]))
            f.write((0).to_bytes(4, "big"))
            f.write(int(generated_at).to_bytes(4, "big"))
            return
        base = primes[0]
        base_bytes = base.to_bytes(max(1, (base.bit_length() + 7) // 8), "big")
        if len(base_bytes) > 255:
            raise ValueError(f"base prime too large for 1-byte length prefix: {base}")
        f.write(bytes([len(base_bytes)]))
        f.write(base_bytes)
        f.write(count.to_bytes(4, "big"))
        f.write(int(generated_at).to_bytes(4, "big"))
        prev = base
        for p in primes[1:]:
            f.write(encode_varint(p - prev))
            prev = p


def format_offset(n):
    """Duplicated verbatim from prime_sieve_v3.py."""
    if n == 0:
        return "0"
    if n % 1_000_000 == 0:
        return f"{n // 1_000_000}M"
    if n % 1_000 == 0:
        return f"{n // 1_000}k"
    if n >= 1_000_000:
        return f"{n / 1_000_000:.6f}M".rstrip('0').rstrip('.')
    if n >= 1_000:
        return f"{n / 1_000:.3f}k".rstrip('0').rstrip('.')
    return str(n)


SCAN_METRICS_FILENAME = "last_scan_metrics.json"


def write_scan_metrics_handoff(portal_folder, total_primes_found=None, windows_processed=None,
                                write_files=None):
    """Trimmed variant of prime_sieve_v3.py's function of the same name: this engine has no
    L_final / sieving_primes_count concept -- primesieve's own generate_primes() call has no
    equivalent diagnostic exposed at this API level (it is not built out of a "sieving
    primes up to sqrt" step this project's own code ever sees) -- so those two keys are
    simply omitted here rather than written out as a misleading None."""
    import json
    path = os.path.join(portal_folder, SCAN_METRICS_FILENAME)
    data = {}
    if total_primes_found is not None:
        data["total_primes_found"] = total_primes_found
    if windows_processed is not None:
        data["windows_processed"] = windows_processed
    if write_files is not None:
        data["write_files"] = write_files
    try:
        os.makedirs(portal_folder, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f)
    except OSError as e:
        print(f"[!] WARNING: could not write scan metrics handoff ({e})")


LOW_FLOOR_CUTOFF = 7  # Duplicated from prime_sieve_v3.py -- see that file's own constant for
                      # the full rationale (floors 0-6 are each narrower than the smallest
                      # supported window_m, 10,000,000).


def _low_floor_segments(base_power, combined_lo, combined_hi):
    """Ported verbatim from prime_sieve_v3.py -- see that file's docstring for the full
    rationale (splits a low-floor combined range by REAL floor boundary instead of writing
    one window that numerically bleeds across several floors)."""
    if base_power >= LOW_FLOOR_CUTOFF or combined_lo != 10 ** base_power:
        return []
    segments = []
    floor = base_power
    while True:
        floor_lo = 10 ** floor
        floor_hi = 10 ** (floor + 1)
        if floor_hi > combined_hi:
            break
        segments.append((floor, floor_lo, floor_hi))
        floor += 1
    return segments


# ------------------------------------------------------------------------------------------
# libprimesieve C API binding -- ctypes, straight against the SYSTEM-installed shared library
# (located via ctypes.util.find_library), NOT one of this project's own .c wrapper engines.
#
# primesieve_generate_primes(start, stop, &size, type) -- note the INCLUSIVE [start, stop]
# range (primesieve's own convention) vs. this project's usual EXCLUSIVE [lo, hi) convention
# used everywhere else in this codebase (windows, floors, combined ranges) -- the one call
# site below (generate_primes_in_range) converts explicitly at the boundary (stop = hi - 1)
# rather than silently mixing the two. Returns a malloc'd array of the requested type;
# primesieve_free() is called on it, after its contents are copied into a plain Python list,
# before this module hands control back to its caller -- nothing here keeps a reference to
# primesieve's own malloc'd memory past generate_primes_in_range() returning.
#
# Source: https://github.com/kimwalisch/primesieve -- include/primesieve.h and
# doc/C_API.md in that repository.
# ------------------------------------------------------------------------------------------

UINT64_PRIMES = 13  # enum value in primesieve.h -- 0-indexed by declaration order: SHORT=0
                     # USHORT=1 INT=2 UINT=3 LONG=4 ULONG=5 LONGLONG=6 ULONGLONG=7 INT16=8
                     # UINT16=9 INT32=10 UINT32=11 INT64=12 UINT64=13. UINT64 (not INT64) is
                     # required here -- floor 19 and above hold values past 2**63-1, which
                     # would silently overflow a signed 64-bit slot.

_lib = None


def _load_lib():
    global _lib
    if _lib is None:
        lib_path = ctypes.util.find_library("primesieve")
        if not lib_path:
            # find_library() can fail to locate an SONAME-versioned .so on some distros even
            # when the library is genuinely installed -- fall back to the plain unversioned
            # name a -dev package's linker script normally provides.
            lib_path = "libprimesieve.so"
        try:
            lib = ctypes.CDLL(lib_path, use_errno=True)
        except OSError as e:
            raise RuntimeError(
                f"Could not load libprimesieve ({lib_path}): {e}. Install it first (e.g. "
                f"'apt install libprimesieve-dev', or build from "
                f"https://github.com/kimwalisch/primesieve) -- this mode calls the system "
                f"library directly; unlike this project's other engines, it does not link "
                f"its own .c wrapper.") from e
        lib.primesieve_generate_primes.argtypes = [
            ctypes.c_uint64, ctypes.c_uint64, ctypes.POINTER(ctypes.c_size_t), ctypes.c_int]
        lib.primesieve_generate_primes.restype = ctypes.c_void_p
        lib.primesieve_free.argtypes = [ctypes.c_void_p]
        lib.primesieve_free.restype = None
        lib.primesieve_get_max_stop.argtypes = []
        lib.primesieve_get_max_stop.restype = ctypes.c_uint64
        lib.primesieve_version.argtypes = []
        lib.primesieve_version.restype = ctypes.c_char_p
        _lib = lib
    return _lib


def primesieve_max_stop():
    """The uint64_t ceiling libprimesieve itself reports (primesieve_get_max_stop()) --
    read directly from the library rather than hardcoded, so this stays correct even if a
    future primesieve version ever changes it. Currently always 2**64 - 1
    (18,446,744,073,709,551,615), which falls in the middle of floor 19, not at a floor
    boundary."""
    return int(_load_lib().primesieve_get_max_stop())


def primesieve_lib_version():
    return _load_lib().primesieve_version().decode("ascii")


def generate_primes_in_range(lo, hi):
    """Returns a sorted Python list of every prime in the EXCLUSIVE range [lo, hi) (this
    project's own convention) by calling primesieve_generate_primes(lo, hi - 1, ...)
    (primesieve's own INCLUSIVE convention) exactly once -- no batching, no chunking on the
    generation side, matching this mode's whole point (see module header).

    The returned buffer is copied into a plain Python list of native ints, then freed
    (primesieve_free) before this function returns.

    Caller is responsible for ensuring hi - 1 <= primesieve_max_stop() -- this function does
    not clamp; see generate_floor_windows()'s ceiling check, which is the one place that
    decision belongs (it also has to report the truncation to the user)."""
    if hi <= lo:
        return []
    lib = _load_lib()
    size = ctypes.c_size_t(0)
    ctypes.set_errno(0)
    ptr = lib.primesieve_generate_primes(lo, hi - 1, ctypes.byref(size), UINT64_PRIMES)
    if not ptr:
        errno = ctypes.get_errno()
        if errno != 0:
            raise RuntimeError(
                f"primesieve_generate_primes({lo}, {hi - 1}) failed (errno={errno})")
        return []
    try:
        arr = (ctypes.c_uint64 * size.value).from_address(ptr)
        primes = list(arr)
    finally:
        lib.primesieve_free(ptr)
    return primes


def generate_floor_windows(base_power, target_idx_start, target_idx_count, window_m,
                            write_files=True, portal_folder=None):
    """Primesieve-direct equivalent of prime_sieve_v3.py's main_batch_scanner(): generates
    the SAME combined range [combined_lo, combined_hi) a target_idx_list would cover there,
    but via ONE primesieve_generate_primes() call instead of this project's own batched/
    parallel sieve engine, then splits the sorted result into window_m-sized files exactly
    as main_batch_scanner's own write-tail does, using the IDENTICAL PGS2 write_prime_
    window() format/filename convention -- files this mode writes are fully interchangeable
    with ones any other engine in this folder wrote, and vice versa.

    Clamps combined_hi to primesieve_max_stop() + 1 (i.e. to what primesieve can actually
    generate) when the request would otherwise exceed it -- prints a clear WARNING when this
    happens, explaining the library's uint64 ceiling and that Floor/Range/Exploration mode
    (the other engines in this folder, which have no such ceiling) should be used for
    anything past it. The clamp can leave the LAST window narrower than window_m -- that is
    still written complete for whatever it DOES cover (never anything past combined_hi, so
    never mislabeled) -- find_continuation_target_idx (prime_atlas_v1.py) only ever reads a
    window's offset from its FILENAME, never its content size, so a narrower-than-usual
    final window does not confuse continuation/browsing anywhere else in this application.

    Low floors (base_power < LOW_FLOOR_CUTOFF) are split by REAL floor boundary via
    _low_floor_segments(), same as every other engine in this folder."""
    BASE = 10 ** base_power
    combined_lo = BASE + target_idx_start * window_m
    combined_hi = combined_lo + target_idx_count * window_m

    max_stop = primesieve_max_stop()
    truncated_by_ceiling = (combined_hi - 1) > max_stop
    if truncated_by_ceiling:
        combined_hi = max_stop + 1

    print("=" * 70)
    print(f"[*] PRIME SIEVE -- {VERSION} (primesieve mode: calls libprimesieve's own "
          f"primesieve_generate_primes() directly -- see this file's header for "
          f"attribution/source: github.com/kimwalisch/primesieve, BSD license)")
    print(f"[*] libprimesieve version: {primesieve_lib_version()}")
    print(f"[*] Combined range: [{combined_lo:,}, {combined_hi:,})  "
          f"size={max(0, combined_hi - combined_lo):,}")
    if truncated_by_ceiling:
        print(f"[!] WARNING: requested range extends past libprimesieve's own uint64 "
              f"ceiling (primesieve_get_max_stop() = {max_stop:,}). Result TRUNCATED to "
              f"that limit -- anything above {max_stop:,} was NOT generated this run. Use "
              f"Floor, Range, or Exploration mode instead for numbers past this point -- "
              f"they have no such ceiling, at the cost of being slower than this mode.")
    if not write_files:
        print(f"[*] WRITE_FILES=False -- no PGS2 files will be written this run; only the "
              f"aggregate prime count will be reported.")
    print("=" * 70)

    if combined_hi <= combined_lo:
        print("[*] Nothing to generate (range is empty after the ceiling clamp).")
        write_scan_metrics_handoff(portal_folder, total_primes_found=0, windows_processed=0,
                                    write_files=write_files)
        print("=" * 70)
        return

    t_start = time.perf_counter()
    primes = generate_primes_in_range(combined_lo, combined_hi)
    t_gen = time.perf_counter() - t_start
    print(f"[*] libprimesieve generated {len(primes):,} primes in {t_gen:.2f}s.")

    generated_at = int(time.time())
    total_primes_found = 0
    windows_processed = 0

    low_floor_segments = _low_floor_segments(base_power, combined_lo, combined_hi)
    if low_floor_segments:
        for floor, floor_lo, floor_hi in low_floor_segments:
            lo_i = bisect.bisect_left(primes, floor_lo)
            hi_i = bisect.bisect_left(primes, floor_hi)
            segment = primes[lo_i:hi_i]
            count = len(segment)
            if write_files:
                folder = os.path.join(portal_folder, f"10p{floor}", "source_primes")
                os.makedirs(folder, exist_ok=True)
                path = os.path.join(folder, f"PRIME_WINDOW_10p{floor}_off_0.bin")
                write_prime_window(path, segment, generated_at=generated_at)
            total_primes_found += count
            windows_processed += 1
            print(f"    10p{floor}: {count:,} primes")
        skipped_floor = low_floor_segments[-1][0] + 1
        print(f"[*] Low-floor batch: floor(s) {low_floor_segments[0][0]}-"
              f"{low_floor_segments[-1][0]} written complete -- floor {skipped_floor} would "
              f"be cut off by this batch's range, so it was skipped (not written partially).")
    else:
        floor_folder = os.path.join(portal_folder, f"10p{base_power}", "source_primes")
        if write_files:
            os.makedirs(floor_folder, exist_ok=True)
        window_lo = combined_lo
        while window_lo < combined_hi:
            window_hi = min(window_lo + window_m, combined_hi)
            lo_i = bisect.bisect_left(primes, window_lo)
            hi_i = bisect.bisect_left(primes, window_hi)
            segment = primes[lo_i:hi_i]
            if write_files:
                offset = window_lo - BASE
                target_tag = f"10p{base_power}_off_{format_offset(offset)}"
                path = os.path.join(floor_folder, f"PRIME_WINDOW_{target_tag}.bin")
                write_prime_window(path, segment, generated_at=generated_at)
            total_primes_found += len(segment)
            windows_processed += 1
            window_lo = window_hi

    print(f"\n[*] TOTAL PRIMES FOUND this run: {total_primes_found:,} across "
          f"{windows_processed} window(s)"
          + ("" if write_files else "  (NO FILES WRITTEN -- count-only mode)"))
    write_scan_metrics_handoff(portal_folder, total_primes_found=total_primes_found,
                                windows_processed=windows_processed, write_files=write_files)
    print("=" * 70)


if __name__ == "__main__":
    print("=" * 70)
    print(f"[*] PRIME SIEVE -- PRIMESIEVE MODE -- {VERSION}")
    print("    Calls libprimesieve's own primesieve_generate_primes() directly -- see this "
          "file's module header for attribution/source "
          "(github.com/kimwalisch/primesieve, BSD license, (C) Kim Walisch).")
    print("=" * 70)

    # CONSTELLATION_PORTAL_DIR: the GUI's Settings tab lets the user point the whole portal
    # at a different disk/folder. When it launches this script as a WSL subprocess it sets
    # this env var; if unset, falls back to the original hardcoded default so any manual WSL
    # invocation keeps working unaffected. Same convention as every other engine in this
    # folder -- see prime_sieve_v3.py's __main__ block.
    env_override = os.environ.get("CONSTELLATION_PORTAL_DIR")
    if env_override:
        BASE_STORAGE_10PN = env_override
    elif os.name == "nt":
        BASE_STORAGE_10PN = r"C:\CONSTELLATION_PORTAL"
    else:
        BASE_STORAGE_10PN = "/mnt/c/CONSTELLATION_PORTAL"
    print(f"[*] Windows written to: {BASE_STORAGE_10PN}\\10p{{N}}\\source_primes\\")

    # CLI: <base_exponent> <target_idx_start> <target_idx_count> <window_m> [write_files 0/1]
    # -- deliberately simpler than prime_sieve_v3.py/v4.py's CLI (no workers/batches_per_
    # worker/compute_sieving_primes_count -- none of those apply to this engine, see module
    # header). All 4 required positions are always passed explicitly by the GUI, never
    # conditionally omitted (same discipline build_loop_argv()'s own docstring describes).
    if len(sys.argv) > 4:
        base_exponent = int(sys.argv[1])
        target_idx_start = int(sys.argv[2])
        target_idx_count = int(sys.argv[3])
        window_m = int(sys.argv[4])
    else:
        base_exponent = 10
        target_idx_start = 0
        target_idx_count = 1
        window_m = 10 ** 7

    write_files = True
    if len(sys.argv) > 5:
        write_files = bool(int(sys.argv[5]))

    print("Start time:", datetime.datetime.now().strftime("%H:%M:%S"))
    generate_floor_windows(base_exponent, target_idx_start, target_idx_count, window_m,
                            write_files=write_files, portal_folder=BASE_STORAGE_10PN)
