name = "StructuralBertrand"
version = "0.1.0"
defaultTargets = ["StructuralBertrand"]

[[lean_lib]]
name = "StructuralBertrand"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"
