name = "RamanujanNested"
version = "0.1.0"
defaultTargets = ["RamanujanNested"]

[[lean_lib]]
name = "RamanujanNested"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.14.0"
